language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t johnthecaptain23/react-client ./client
  - docker build -t johnthecaptain23/react-nginx ./nginx
  - docker build -t johnthecaptain23/react-server ./server
  - docker build -t johnthecaptain23/react-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push johnthecaptain23/react-client
  - docker push johnthecaptain23/react-nginx
  - docker push johnthecaptain23/react-server
  - docker push johnthecaptain23/react-worker
  
