language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t jaykay/react-client ./client
  - docker build -t jaykay/react-nginx ./nginx
  - docker build -t jaykay/react-server ./server
  - docker build -t jaykay/react-worker ./worker

